/**
 * FileTransparencyService - Agent Memory System v1.5
 * Provides bidirectional sync between database and user-editable Markdown files
 */

import { promises as fs } from 'fs';
import * as path from 'path';
import { ProjectMemory, SharedContext, LearnedPattern } from '../types/memory';
import { projectMemoryService } from './ProjectMemoryService';

// Use posix paths for cross-platform consistency
const posixPath = path.posix;

export interface TransparencyConfig {
  outputDir: string;
  autoExport: {
    onSessionEnd: boolean;
    onPatternLearned: boolean;
  };
}

export const DEFAULT_TRANSPARENCY_CONFIG: TransparencyConfig = {
  outputDir: '.andos/memory',
  autoExport: {
    onSessionEnd: true,
    onPatternLearned: true,
  },
};

export interface EditableSection {
  path: string;
  content: string;
}

export interface SessionSummary {
  sessionId: string;
  date: string;
  summary: string;
  decisions: string[];
  patterns: string[];
}

export class FileTransparencyService {
  private config: TransparencyConfig;

  constructor(config: TransparencyConfig = DEFAULT_TRANSPARENCY_CONFIG) {
    this.config = config;
  }

  /**
   * Export all project memory to Markdown files
   */
  async exportAll(
    projectId: string,
    projectRoot: string,
    sessions?: SessionSummary[]
  ): Promise<void> {
    await this.exportProjectMemory(projectId, projectRoot);

    if (sessions && sessions.length > 0) {
      await this.exportSessionSummaries(sessions, projectRoot);
    }
  }

  /**
   * Export project memory to PROJECT_MEMORY.md
   */
  async exportProjectMemory(projectId: string, projectRoot: string): Promise<void> {
    const memory = await projectMemoryService.getProjectMemory(projectId);
    const patterns = await projectMemoryService.getProjectPatterns(projectId);
    const content = this.formatProjectMemory(memory, patterns);
    const outputPath = posixPath.join(projectRoot, this.config.outputDir, 'PROJECT_MEMORY.md');
    await fs.mkdir(posixPath.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, content, 'utf-8');
  }

  /**
   * Export session summaries to sessions/YYYY-MM-DD.md
   */
  async exportSessionSummaries(sessions: SessionSummary[], projectRoot: string): Promise<void> {
    const sessionsDir = posixPath.join(projectRoot, this.config.outputDir, 'sessions');
    await fs.mkdir(sessionsDir, { recursive: true });

    // Group sessions by date
    const sessionsByDate = new Map<string, SessionSummary[]>();
    for (const session of sessions) {
      if (!sessionsByDate.has(session.date)) {
        sessionsByDate.set(session.date, []);
      }
      sessionsByDate.get(session.date)!.push(session);
    }

    // Write each date's sessions
    for (const [date, dateSessions] of sessionsByDate) {
      const content = this.formatSessionSummary(date, dateSessions);
      const outputPath = posixPath.join(sessionsDir, `${date}.md`);
      await fs.writeFile(outputPath, content, 'utf-8');
    }
  }

  /**
   * Format session summary as Markdown
   */
  private formatSessionSummary(date: string, sessions: SessionSummary[]): string {
    const parts: string[] = [];

    parts.push(`# Session Summary: ${date}`);
    parts.push('');

    for (const session of sessions) {
      parts.push(`## Session: ${session.sessionId}`);
      parts.push('');
      parts.push(`**Session ID:** ${session.sessionId}`);
      parts.push('');
      parts.push('### Overview');
      parts.push('');
      parts.push(session.summary);
      parts.push('');

      if (session.decisions.length > 0) {
        parts.push('### Decisions Made');
        parts.push('');
        for (const decision of session.decisions) {
          parts.push(`- ${decision}`);
        }
        parts.push('');
      }

      if (session.patterns.length > 0) {
        parts.push('### Patterns Observed');
        parts.push('');
        for (const pattern of session.patterns) {
          parts.push(`- ${pattern}`);
        }
        parts.push('');
      }

      parts.push('---');
      parts.push('');
    }

    parts.push('*Auto-generated by ANDOS File Transparency Layer*');

    return parts.join('\n');
  }

  /**
   * Format project memory as Markdown
   */
  formatProjectMemory(memory: ProjectMemory, patterns?: LearnedPattern[]): string {
    const parts: string[] = [];

    // Header with metadata comment block
    parts.push(`# Project Memory: ${memory.project_id}`);
    parts.push('');
    parts.push('<!--');
    parts.push('ANDOS_MEMORY_FILE');
    parts.push(`Type: PROJECT_MEMORY`);
    parts.push(`Project: ${memory.project_id}`);
    parts.push(`Version: ${memory.version}`);
    parts.push(`Last Updated: ${memory.updated_at.toISOString().split('T')[0]}`);
    parts.push('-->');
    parts.push('');

    const ctx = memory.shared_context;

    // Code Style Preferences
    if (ctx.code_style_preferences) {
      parts.push('## Code Style Preferences');
      parts.push('');

      const prefs = ctx.code_style_preferences;

      if (prefs.naming_conventions && Object.keys(prefs.naming_conventions).length > 0) {
        parts.push('### Naming Conventions');
        parts.push('');
        parts.push('<!-- EDITABLE_SECTION: code_style_preferences.naming_conventions -->');
        for (const [key, value] of Object.entries(prefs.naming_conventions)) {
          parts.push(`- ${key}: ${value}`);
        }
        parts.push('<!-- END_EDITABLE_SECTION -->');
        parts.push('');
      }

      if (prefs.formatting_rules && Object.keys(prefs.formatting_rules).length > 0) {
        parts.push('### Formatting Rules');
        parts.push('');
        parts.push('<!-- EDITABLE_SECTION: code_style_preferences.formatting_rules -->');
        for (const [key, value] of Object.entries(prefs.formatting_rules)) {
          parts.push(`- ${key}: ${value}`);
        }
        parts.push('<!-- END_EDITABLE_SECTION -->');
        parts.push('');
      }

      if (prefs.language_specific && Object.keys(prefs.language_specific).length > 0) {
        parts.push('### Language Specific');
        parts.push('');
        parts.push('<!-- EDITABLE_SECTION: code_style_preferences.language_specific -->');
        for (const [lang, rules] of Object.entries(prefs.language_specific)) {
          parts.push(`#### ${lang}`);
          if (typeof rules === 'object' && rules !== null) {
            for (const [key, value] of Object.entries(rules)) {
              parts.push(`- ${key}: ${value}`);
            }
          }
          parts.push('');
        }
        parts.push('<!-- END_EDITABLE_SECTION -->');
        parts.push('');
      }
    }

    // API Patterns
    if (ctx.api_patterns && ctx.api_patterns.length > 0) {
      parts.push('## API Patterns');
      parts.push('');
      parts.push('<!-- EDITABLE_SECTION: api_patterns -->');
      for (const pattern of ctx.api_patterns) {
        parts.push(`### ${pattern.name}`);
        parts.push('');
        parts.push(pattern.description);
        parts.push('');
        if (pattern.usage_examples && pattern.usage_examples.length > 0) {
          parts.push('**Usage Examples:**');
          parts.push('');
          for (const example of pattern.usage_examples) {
            const bt1 = '`';
            parts.push(`- ${bt1}${example}${bt1}`);
          }
          parts.push('');
        }
        if (pattern.preferred_over && pattern.preferred_over.length > 0) {
          parts.push(`**Preferred over:** ${pattern.preferred_over.join(', ')}`);
          parts.push('');
        }
      }
      parts.push('<!-- END_EDITABLE_SECTION -->');
      parts.push('');
    }

    // Common Errors
    if (ctx.common_errors && ctx.common_errors.length > 0) {
      parts.push('## Common Errors');
      parts.push('');
      parts.push('<!-- EDITABLE_SECTION: common_errors -->');
      for (const error of ctx.common_errors) {
        parts.push(`### ${error.pattern}`);
        parts.push('');
        parts.push(`**Solution:** ${error.solution}`);
        parts.push('');
        parts.push(`**Prevention:** ${error.prevention}`);
        parts.push('');
        if (error.examples && error.examples.length > 0) {
          parts.push('**Examples:**');
          parts.push('');
          for (const example of error.examples) {
            const bt2 = '`';
          parts.push(`- ${bt2}${example}${bt2}`);
          }
          parts.push('');
        }
      }
      parts.push('<!-- END_EDITABLE_SECTION -->');
      parts.push('');
    }

    // Team Conventions
    if (ctx.team_conventions && ctx.team_conventions.length > 0) {
      parts.push('## Team Conventions');
      parts.push('');
      parts.push('<!-- EDITABLE_SECTION: team_conventions -->');
      for (const convention of ctx.team_conventions) {
        parts.push(`- **${convention.category}**: ${convention.rule}`);
        parts.push(`  - Rationale: ${convention.rationale}`);
        parts.push('');
      }
      parts.push('<!-- END_EDITABLE_SECTION -->');
      parts.push('');
    }

    // Architecture Decisions
    if (ctx.architecture_decisions && ctx.architecture_decisions.length > 0) {
      parts.push('## Architecture Decisions');
      parts.push('');
      parts.push('<!-- EDITABLE_SECTION: architecture_decisions -->');
      for (const decision of ctx.architecture_decisions) {
        parts.push(`### ${decision.decision}`);
        parts.push('');
        parts.push(`**Date:** ${decision.date.toISOString().split('T')[0]}`);
        parts.push('');
        parts.push(`**Context:** ${decision.context}`);
        parts.push('');
        parts.push('**Consequences:**');
        parts.push('');
        for (const consequence of decision.consequences) {
          parts.push(`- ${consequence}`);
        }
        parts.push('');
      }
      parts.push('<!-- END_EDITABLE_SECTION -->');
      parts.push('');
    }

    // Learned Patterns
    if (patterns && patterns.length > 0) {
      parts.push('## Learned Patterns');
      parts.push('');
      parts.push('*These patterns are automatically learned from code analysis*');
      parts.push('');
      for (const pattern of patterns) {
        parts.push(`### ${pattern.name}`);
        parts.push('');
        parts.push(`- **Type:** ${pattern.type}`);
        parts.push(`- **Frequency:** ${pattern.frequency}`);
        parts.push(`- **Confidence:** ${Math.round(pattern.confidence * 100)}%`);
        if (pattern.description) {
          parts.push(`- **Description:** ${pattern.description}`);
        }
        parts.push(`- **Last Observed:** ${pattern.last_observed_at.toISOString().split('T')[0]}`);
        parts.push('');
      }
    }

    parts.push('---');
    parts.push('');
    parts.push('*This file is managed by ANDOS. Editable sections are marked with HTML comments.*');

    return parts.join('\n');
  }

  /**
   * Sync user edits from file back to database
   */
  async syncFromFile(filePath: string): Promise<void> {
    const content = await fs.readFile(filePath, 'utf-8');
    const parsed = this.parseProjectMemory(content);

    if (!parsed.project_id) {
      throw new Error('Invalid PROJECT_MEMORY.md: missing project_id');
    }

    // Apply updates to database
    if (parsed.shared_context) {
      await projectMemoryService.updateProjectContext(parsed.project_id, parsed.shared_context);
    }
  }

  /**
   * Detect editable sections in markdown content
   */
  detectEditableSections(content: string): EditableSection[] {
    const sections: EditableSection[] = [];
    const regex = /<!-- EDITABLE_SECTION: ([\w.]+) -->\n([\s\S]*?)<!-- END_EDITABLE_SECTION -->/g;

    let match: RegExpExecArray | null;
    while ((match = regex.exec(content)) !== null) {
      sections.push({
        path: match[1],
        content: match[2].trim(),
      });
    }

    return sections;
  }

  /**
   * Parse PROJECT_MEMORY.md content
   */
  parseProjectMemory(content: string): Partial<ProjectMemory> {
    if (!content.trim()) {
      return {};
    }

    const result: Partial<ProjectMemory> = {
      shared_context: {},
    };

    // Parse metadata from HTML comment
    const metaMatch = content.match(/Project: ([\w-]+)/);
    if (metaMatch) {
      result.project_id = metaMatch[1];
    }

    const versionMatch = content.match(/Version: (\d+)/);
    if (versionMatch) {
      result.version = parseInt(versionMatch[1], 10);
    }

    // Parse editable sections (from files written by this service)
    const sections = this.detectEditableSections(content);
    const ctx: SharedContext = {};

    for (const section of sections) {
      if (section.path.startsWith('code_style_preferences')) {
        if (!ctx.code_style_preferences) {
          ctx.code_style_preferences = {
            naming_conventions: {},
            formatting_rules: {},
            language_specific: {},
          };
        }

        const subPath = section.path.replace('code_style_preferences.', '');

        if (subPath === 'naming_conventions' || subPath === 'code_style_preferences') {
          ctx.code_style_preferences.naming_conventions = this.parseKeyValueList(section.content);
        } else if (subPath === 'formatting_rules') {
          ctx.code_style_preferences.formatting_rules = this.parseKeyValueList(section.content);
        } else if (subPath === 'language_specific') {
          ctx.code_style_preferences.language_specific = this.parseLanguageSpecific(section.content);
        }
      } else if (section.path === 'api_patterns') {
        ctx.api_patterns = this.parseAPIPatterns(section.content);
      } else if (section.path === 'common_errors') {
        ctx.common_errors = this.parseCommonErrors(section.content);
      } else if (section.path === 'team_conventions') {
        ctx.team_conventions = this.parseTeamConventions(section.content);
      } else if (section.path === 'architecture_decisions') {
        ctx.architecture_decisions = this.parseArchitectureDecisions(section.content);
      }
    }

    // Also parse markdown directly (for files without editable markers)
    // Parse code style preferences
    if (content.includes('## Code Style Preferences') && !ctx.code_style_preferences) {
      ctx.code_style_preferences = this.parseCodeStylePreferences(content);
    }

    // Parse team conventions
    if (content.includes('## Team Conventions') && !ctx.team_conventions) {
      ctx.team_conventions = this.parseTeamConventions(content);
    }

    // Parse architecture decisions
    if (content.includes('## Architecture Decisions') && !ctx.architecture_decisions) {
      ctx.architecture_decisions = this.parseArchitectureDecisions(content);
    }

    // Parse API patterns
    if (content.includes('## API Patterns') && !ctx.api_patterns) {
      ctx.api_patterns = this.parseAPIPatterns(content);
    }

    // Parse common errors
    if (content.includes('## Common Errors') && !ctx.common_errors) {
      ctx.common_errors = this.parseCommonErrors(content);
    }

    if (Object.keys(ctx).length > 0) {
      result.shared_context = ctx;
    }

    return result;
  }

  /**
   * Parse key-value list from markdown
   */
  private parseKeyValueList(content: string): Record<string, any> {
    const result: Record<string, any> = {};
    const lines = content.split('\n');

    for (const line of lines) {
      const match = line.match(/^- ([\w_]+):\s*(.+)$/);
      if (match) {
        const value = match[2];
        // Try to parse as number or boolean
        if (value === 'true') {
          result[match[1]] = true;
        } else if (value === 'false') {
          result[match[1]] = false;
        } else if (/^\d+$/.test(value)) {
          result[match[1]] = parseInt(value, 10);
        } else {
          result[match[1]] = value;
        }
      }
    }

    return result;
  }

  /**
   * Parse code style preferences from markdown section
   */
  private parseCodeStylePreferences(content: string): any {
    const result = {
      naming_conventions: {},
      formatting_rules: {},
      language_specific: {},
    };

    // Extract naming conventions section
    const namingMatch = content.match(/### Naming Conventions\n+([\s\S]*?)(?=###|$)/);
    if (namingMatch) {
      result.naming_conventions = this.parseKeyValueList(namingMatch[1]);
    }

    // Extract formatting rules section
    const formattingMatch = content.match(/### Formatting Rules\n+([\s\S]*?)(?=###|$)/);
    if (formattingMatch) {
      result.formatting_rules = this.parseKeyValueList(formattingMatch[1]);
    }

    return result;
  }

  /**
   * Parse language-specific settings
   */
  private parseLanguageSpecific(content: string): Record<string, any> {
    const result: Record<string, any> = {};
    const lines = content.split('\n');
    let currentLang: string | null = null;

    for (const line of lines) {
      const headerMatch = line.match(/^#### (.+)$/);
      if (headerMatch) {
        currentLang = headerMatch[1];
        result[currentLang] = {};
      } else if (currentLang) {
        const kvMatch = line.match(/^- ([\w_]+):\s*(.+)$/);
        if (kvMatch) {
          const value = kvMatch[2];
          if (value === 'true') {
            result[currentLang][kvMatch[1]] = true;
          } else if (value === 'false') {
            result[currentLang][kvMatch[1]] = false;
          } else if (/^\d+$/.test(value)) {
            result[currentLang][kvMatch[1]] = parseInt(value, 10);
          } else {
            result[currentLang][kvMatch[1]] = value;
          }
        }
      }
    }

    return result;
  }

  /**
   * Parse API patterns from markdown
   */
  private parseAPIPatterns(content: string): any[] {
    const patterns: any[] = [];
    const sections = content.split(/### (.+)\n/).slice(1);

    for (let i = 0; i < sections.length; i += 2) {
      if (i + 1 >= sections.length) break;

      const name = sections[i].trim();
      const body = sections[i + 1];

      const pattern: any = { name, description: '', usage_examples: [] };

      const lines = body.split('\n').filter(l => l.trim());
      if (lines.length > 0) {
        pattern.description = lines[0].trim();
      }

      // Extract usage examples
      const exampleMatch = body.match(/\*\*Usage Examples:\*\*\n+([\s\S]*?)(?=\*\*Preferred over|\n\n|$)/);
      if (exampleMatch) {
        const examples = exampleMatch[1].match(/- `(.+)`/g);
        if (examples) {
          pattern.usage_examples = examples.map(e => e.replace(/- `(.+)`/, '$1'));
        }
      }

      // Extract preferred_over
      const preferredMatch = body.match(/\*\*Preferred over:\*\* (.+)/);
      if (preferredMatch) {
        pattern.preferred_over = preferredMatch[1].split(',').map(s => s.trim());
      }

      patterns.push(pattern);
    }

    return patterns;
  }

  /**
   * Parse common errors from markdown
   */
  private parseCommonErrors(content: string): any[] {
    const errors: any[] = [];
    const sections = content.split(/### (.+)\n/).slice(1);

    for (let i = 0; i < sections.length; i += 2) {
      if (i + 1 >= sections.length) break;

      const pattern = sections[i].trim();
      const body = sections[i + 1];

      const error: any = { pattern, solution: '', prevention: '', examples: [] };

      const solutionMatch = body.match(/\*\*Solution:\*\* (.+)/);
      if (solutionMatch) {
        error.solution = solutionMatch[1].trim();
      }

      const preventionMatch = body.match(/\*\*Prevention:\*\* (.+)/);
      if (preventionMatch) {
        error.prevention = preventionMatch[1].trim();
      }

      const examplesMatch = body.match(/\*\*Examples:\*\*\n+([\s\S]*?)(?=\n\n|$)/);
      if (examplesMatch) {
        const examples = examplesMatch[1].match(/- `(.+)`/g);
        if (examples) {
          error.examples = examples.map(e => e.replace(/- `(.+)`/, '$1'));
        }
      }

      errors.push(error);
    }

    return errors;
  }

  /**
   * Parse team conventions from markdown
   */
  private parseTeamConventions(content: string): any[] {
    const conventions: any[] = [];
    const lines = content.split('\n');

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const match = line.match(/^- \*\*(.+?)\*\*:\s*(.+)$/);
      if (match) {
        const convention: any = {
          category: match[1],
          rule: match[2],
          rationale: '',
        };

        // Check next line for rationale
        if (i + 1 < lines.length) {
          const rationaleMatch = lines[i + 1].match(/^\s+- Rationale:\s*(.+)$/);
          if (rationaleMatch) {
            convention.rationale = rationaleMatch[1];
          }
        }

        conventions.push(convention);
      }
    }

    return conventions;
  }

  /**
   * Parse architecture decisions from markdown
   */
  private parseArchitectureDecisions(content: string): any[] {
    const decisions: any[] = [];
    const sections = content.split(/### (.+)\n/).slice(1);

    for (let i = 0; i < sections.length; i += 2) {
      if (i + 1 >= sections.length) break;

      const decision = sections[i].trim();
      const body = sections[i + 1];

      const decisionObj: any = {
        decision,
        context: '',
        consequences: [],
        date: new Date(),
      };

      // Try both formats: "- **Date**:" and "**Date:**" (with optional leading dash)
      const dateMatch = body.match(/-?\s*\*\*Date\*\*:\s*(\d{4}-\d{2}-\d{2})/);
      if (dateMatch) {
        decisionObj.date = new Date(dateMatch[1]);
      }

      const contextMatch = body.match(/-?\s*\*\*Context\*\*:\s*(.+)/);
      if (contextMatch) {
        decisionObj.context = contextMatch[1].trim();
      }

      const consequencesMatch = body.match(/\*\*Consequences\*\*:\s*\n+([\s\S]*?)(?=\n\n|$)/);
      if (consequencesMatch) {
        const consequences = consequencesMatch[1].match(/^\s*- (.+)$/gm);
        if (consequences) {
          decisionObj.consequences = consequences.map(c => c.replace(/^\s*- /, ''));
        }
      }

      decisions.push(decisionObj);
    }

    return decisions;
  }
}

export const fileTransparencyService = new FileTransparencyService();
